import feedparser
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os

# --- CONFIGURATION ---
# If running locally, replace these with your actual details.
# If running on GitHub, these will be pulled from Secrets.
EMAIL_SENDER = os.environ.get('EMAIL_USER')  
EMAIL_PASSWORD = os.environ.get('EMAIL_PASS') 
EMAIL_RECEIVER = "your_email@gmail.com" # Replace with your email if testing locally

# News Sections & Google News Queries
# we use "when:1d" to ensure we only get news from the last 24 hours
SECTIONS = {
    "🇮🇳 INDIA UPDATES": {
        "Finance & Markets": "India Finance OR Stock Market OR Economy when:1d",
        "Tech & Auto": "India Technology OR Automobile OR Startup when:1d",
        "Politics": "India Politics OR Government when:1d",
        "Entertainment & Lifestyle": "India Bollywood OR Entertainment OR Lifestyle when:1d",
        "Travel": "India Travel OR Tourism when:1d",
        "Sports": "India Cricket OR Sports when:1d"
    },
    "🌍 WORLD UPDATES": {
        "Finance & Markets": "World Economy OR Global Finance OR Stock Market when:1d",
        "Tech & Auto": "Global Technology OR Artificial Intelligence OR Automobile when:1d",
        "Politics": "World Politics OR Geopolitics OR United Nations when:1d",
        "Entertainment & Lifestyle": "Hollywood OR Global Entertainment OR Lifestyle when:1d",
        "Travel": "World Travel OR International Tourism when:1d",
        "Sports": "World Sports OR Football OR Tennis when:1d"
    }
}

def fetch_news(query):
    """Fetches news from Google News RSS for a given query."""
    encoded_query = query.replace(" ", "%20")
    # ceid=IN:en ensures we get English news relevant to India context even for world news
    url = f"https://news.google.com/rss/search?q={encoded_query}&hl=en-IN&gl=IN&ceid=IN:en"
    feed = feedparser.parse(url)
    return feed.entries[:5]  # Get top 5 stories per topic

def create_html_content():
    today_date = datetime.now().strftime("%d %B, %Y")
    
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto;">
        <div style="background-color: #2c3e50; color: white; padding: 20px; text-align: center;">
            <h1 style="margin:0;">The Daily Briefing</h1>
            <p style="margin:5px;">{today_date} | Your Personal Newspaper</p>
        </div>
    """

    for main_section, sub_sections in SECTIONS.items():
        html += f"""
        <div style="margin-top: 30px; border-bottom: 2px solid #2c3e50;">
            <h2 style="color: #c0392b; text-transform: uppercase;">{main_section}</h2>
        </div>
        """
        
        for topic, query in sub_sections.items():
            news_items = fetch_news(query)
            if not news_items:
                continue
                
            html += f"<h3 style='background-color: #ecf0f1; padding: 8px; margin-top: 15px;'>{topic}</h3><ul>"
            
            for item in news_items:
                # Clean up the description/summary provided by Google RSS
                summary = item.description if 'description' in item else ""
                # Removes HTML tags from summary if complex, or keep simple
                
                html += f"""
                <li style="margin-bottom: 10px;">
                    <a href="{item.link}" style="text-decoration: none; color: #2980b9; font-weight: bold;">
                        {item.title}
                    </a>
                    <div style="font-size: 12px; color: #555; margin-top: 2px;">
                        {item.source.title if 'source' in item else 'News Source'}
                    </div>
                </li>
                """
            html += "</ul>"

    html += """
        <div style="text-align: center; padding: 20px; font-size: 12px; color: #777;">
            <p>Generated by your Personal AI Newspaper Tool</p>
        </div>
    </body>
    </html>
    """
    return html

def send_email():
    if not EMAIL_SENDER or not EMAIL_PASSWORD:
        print("Error: Email credentials not found.")
        return

    msg = MIMEMultipart()
    msg['From'] = EMAIL_SENDER
    msg['To'] = EMAIL_RECEIVER
    msg['Subject'] = f"📰 Your Daily Briefing: {datetime.now().strftime('%d %b %Y')}"

    html_content = create_html_content()
    msg.attach(MIMEText(html_content, 'html'))

    try:
        # Connect to Gmail SMTP
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        text = msg.as_string()
        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, text)
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    send_email()
